### ISSUE TITLE
提案：`A` 作为韵母 `ia` 的飞键

### ISSUE THREAD

**Issue by OverflowCat** [LemonHX/lemon5code#2]
## 摘要

在双拼方案中，<kbd>A</kbd> 键可以代表音节 `ia`。

## 动机

1. 可以和韵母 `ia` 相拼的声母只有 `j`、`q`、`x`、`l`、`d`、`n`，而 `j`、`q`、`x` 不能和 `a` 相拼，`ia` 与 `l`、`d`、`n` 相拼的字很少¹。
2. <kbd>A</kbd> 比 <kbd>X</kbd> 更好按，尤其是在输入 `qia` 音节时；
3. 减少手指移动距离。

### 方案 1

将 <kbd>X</kbd> 的韵母 `ia` 取消，所有 `ia` 通过 <kbd>A</kbd> 输入。

### 方案 2

支持同时使用 <kbd>A</kbd> 和 <kbd>X</kbd> 代表韵母 `ia`，此时 <kbd>A</kbd> 作为飞键，<kbd>A</kbd> 上有两个韵母 `ia` 和 `a`。

### 方案 3

支持同时使用 <kbd>A</kbd> 和 <kbd>X</kbd> 代表韵母 `ia`，但仅在声母不能和 a 相拼时。这意味着 `俩 lia`、`嗲 dia` 只能分别通过 `lx`、`dx` 输入。

### 方案 4

<kbd>X</kbd> 仅在声母不能和 a 相拼时才作为韵母 `ia`，而声母为 `j`、`q`、`x` 时只能使用  <kbd>A</kbd>。

## 备注

1. 读音为 `lia` 的字有 `兩`、`俩`、`倆`、`𠈓`、`𢎏`<a href="https://zi.tools/?secondary=reading&tab=syllable&lang1=cn&input=lia"><sup>†</sup></a>，读音为 `dia` 的字有 `嗲`、`𪮟`、`𪦕`<a href="https://zi.tools/?secondary=reading&tab=syllable&lang1=cn&input=dia"><sup>†</sup></a>，读音为 `nia` 的字有 `㖸`、`𫾈`<a href="https://zi.tools/?secondary=reading&tab=syllable&lang1=cn&input=nia"><sup>†</sup></a>，其中只有 _俩_ 是常用字：`俩`、`嗲`。

**Comment by LemonHX** [comment]
虾:
下:
亚:
丫:

**Comment by LemonHX** [comment]
可以把 `ax` 作为功能键

**Comment by LemonHX** [comment]
好的~采纳了😄
